app:
  name: в будущем может будет нужно =)
  server-ip:
    dev-front: 192.168.222.22
    dev-gateway: 192.168.222.23
    dev-back: 192.168.222.24

# H2
spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource
  datasource:
    continue-on-error: true
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

